---

php_ldap_password_remote_server: localhost
php_ldap_password_remote_port: 389
php_ldap_password_domain: "{{server_name}}.{{domain_name}}"
php_ldap_password_users_subtree: "ou=mail"
php_ldap_password_login_attributes:
  - uid
  - mail
web_vhost_php_ldap_password: "{{server_name}}.{{domain_name}}"
php_ldap_password_scriptname: changepassword.php
