---

- name: restart spamassassin
  service: name=spamassassin state=restarted

- name: restart opendkim
  service: name=opendkim state=restarted

- name: restart postfix
  service: name=postfix state=restarted

- name: restart postgrey
  service: name=postgrey state=restarted

- name: restart dovecot
  service: name=dovecot state=restarted

- name: update mail aliases
  command: newaliases
