- name: Install VPN-related packages
  apt: pkg={{item}} state=installed
  with_items:
    - openvpn
    - dnsmasq
  tags: vpn

- name: Install OpenVPN server configuration
  template: src=openvpn-server.conf.j2 dest=/etc/openvpn/server.conf owner=root group=root mode=0644
  notify:
    - restart openvpn
  tags: vpn

- name: Install OpenVPN LDAP plugin package
  apt: pkg=openvpn-auth-ldap state=installed
  when: ( openvpn_auth_mech == 'ldap' or openvpn_auth_mech == 'both' )
  tags:
    - vpn

- name: Directory /etc/openvpn/auth
  file: state=directory path=/etc/openvpn/auth owner=root group=root mode=0755
  when: ( openvpn_auth_mech == 'ldap' or openvpn_auth_mech == 'both' )
  tags:
    - vpn

- name: Install LDAP authentification configuration for OpenVPN
  template: src=openvpn-ldapauth-plugin.conf.j2 dest=/etc/openvpn/auth/auth-ldap.conf owner=root group=root mode=0644
  when: ( openvpn_auth_mech == 'ldap' or openvpn_auth_mech == 'both' )
  notify:
    - restart openvpn
  tags:
    - vpn
    - ldap

- name: Create OpenVPN log directory
  file: path=/var/log/openvpn state=directory owner=root group=root mode=0700
  tags: vpn

- name: Set OpenVPN log files permissions
  file: path=/var/log/openvpn/server.{{item}} state=touch owner=root group=root mode=0600
  with_items:
    - status
    - log
  tags: vpn

- name: Install OpenVPN scripts
  copy: src={{item}} dest=/etc/openvpn/ owner=root group=root mode=0755
  with_fileglob:
    - etc/openvpn/server-*.sh
  notify:
    - restart openvpn
  tags: vpn

- name: Install OpenVPN Debian default file
  copy: src=etc/default/openvpn dest=/etc/default/openvpn owner=root group=root mode=0644
  tags: vpn

- name: Install dnsmasq configuration
  copy: src=etc/dnsmasq.d/vpn dest=/etc/dnsmasq.d/vpn group=root owner=root mode=0644
  notify:
    - restart dnsmasq
  tags: vpn
